### ISSUE TITLE
Unable to build with ldc2.exe

### ISSUE THREAD

**Issue by david7a68** [Pure-D/workspace-d#18]
I have LDC installed and have verified that it works. However, the installer still refuses to build. The ldc path string is still null.

**Comment by WebFreak001** [comment]
Can you post the error output? It will probably be fixed in the next dub release/pre-release because there was an issue with LDC on Windows. So it might work with dub 0.9.26 or 1.0.0 once they release any of those. They already fixed it in ~master so you might be able to fix it by compiling dub from force if you want to do it right now.

**Comment by david7a68** [comment]
It's the standard 'could not find LDC' error:

```
LDC is required on your platform!
WARNING: LDC could was not detected. Before submitting an issue, make sure `dub build --compiler=ldc` works!

Which optional dependencies do you want to install?
[1] DCD - auto completion
[2] DScanner - code linting
[3] dfmt - code formatting
Enter a comma separated list of numbers
Selected [all]:
Using existing git repository for workspace-d
Compiling...
$ dub upgrade
Upgrading project in $\USER_PATH\Development\Tools\workspace-d
```

Which I find strange because I entered the getLDC()'s commands manually and I got the version string that way.

**Comment by WebFreak001** [comment]
um I am just gonna add a default value which will make it run `--compiler=ldc` even if no ldc is found
