### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by bubnenkoff** [Pure-D/workspace-d#41]
Could you explain (add to readme) what I should to do if I want to do manual installation? 

Ok. Let's assume I compile it:
`dub build --build=release`
But what next? Should I copy it anywhere or what?

**Comment by WebFreak001** [comment]
You need to compile workspace-d with `dub build --build=release --compiler=ldc` (ldc because of a dmd/phobos bug. We couldnt find a way to reproduce it yet though. See https://github.com/Pure-D/code-d/issues/38#issuecomment-221310734 for further information). If you don't use LDC, the workspace-d implementation/plugin in your IDE/editor will hang up when trying to use anything which isn't built-in

Then you compile `dcd`, `dscanner` and `dfmt` as described in their READMEs. You can skip dfmt for example if you don't want to use the auto formatter feature

When you have all executables either move them all to some single path and add that one to the windows PATH environment variable, add each path to the PATH variable or change the executable path in the config of your editor
