### ISSUE TITLE
[vscode] 2.11.0 very slow compared to 2.10.0

### ISSUE THREAD

**Issue by zorael** [Pure-D/workspace-d#82]
Running Manjaro/Arch linux with workspace-d from the official tarball, and dcd and friends from Arch repositories. Visual Studio Code is 1.14.1 from AUR. (workspace-d was not locally built because of -fPIC relocation errors when linking phobos.)

2.10.0 has always been reasonably fast with tooltips quickly popping up when mouseovering definitions. With 2.11.0 I get a "Loading" tooltip for a full second before the real tooltip is shown.

Looking at htop I see dcd-server spiking up to near 100% even with the editor idle, then dropping down to 5% a second later, then spiking up to 100% again and repeating.

The behaviour is completely reversible by reinstalling 2.10.0. I'm not sure how to profile this unless I can run workspace-d separately.

**Comment by WebFreak001** [comment]
I changed to LDC because of the -fPIC issue for that release, not sure if that is the whole reason. Maybe it happened because of the merge of the single import files though. Try commenting this out https://github.com/Pure-D/workspace-d/blob/master/source/workspaced/com/dub.d#L45-L46 and then recompile using `dub --compiler=ldc --build=release` and see if it still happens?

**Comment by zorael** [comment]
There was a DMD package upgrade to 2.075 and workspace-d properly links with its phobos.

With those lines commented it's fast again, both when compiled with LDC and with DMD. I no longer see the CPU usage spikes either. Without those commented, both are slow.

Are there any negative side-effects to keeping them commented?

**Comment by WebFreak001** [comment]
well I added it to allow single files in dub to be auto completed (like vibe.d instead of only vibe.vibe), I would prefer to keep it. I will check why it is so slow
